EmpireProject/Empire

lib/modules/situational_awareness/host/computerdetails.py, lib/modules/situational_awareness/host/winenum.py
Caught a couple instances of "Host" being used to make the filepath instead of "host", causing Empire to not load the referenced PS1 file.
=> Filepath typos in situational_awareness/host modules

data/agent/agent.ps1, lib/common/agents.py, lib/common/encryption.py
Even though the agent to server communications are encrypted they are still malleable and vulnerable to attack.
The easiest attack is to trick a server into forgetting an agent. Take an encrypted message sniffed from the network and send it to the server 256 times with the first byte replaced so that it has all values 0 through 255. The server sees 256 packets with 256 different types, one is guaranteed to be `TASK_EXIT`.
Because the padding isn't verified there isn't an opportunity for a traditional padding oracle attack. However, there are ways to get the server to decrypt portions of an encrypted packet for you. The only method for doing this I've worked out isn't very efficient or effective though.
Notes some choices I made:
* MD5 to save space in messages over something better, e.g. …
=> Use authenticated encryption

changelog, data/agent/agent.ps1, lib/common/packets.py
Made results get returned base64 so that agent.ps1 works independent of unicode chars in output. Will need revisiting for full unicode output support.
=> International support

lib/modules/persistence/elevated/wmi.py
Before this change, the command
` set SubName `
did not change the event subscription name installed by the agent as instructed by the user.
=> fix hard-coded event subscription name

lib/modules/template.py
Was messing around with module dev earlier and ran across this while using template.py 
(Empire: situational_awareness/host/paranoia) > info
Name: Invoke-Paranoia
Module: situational_awareness/host/paranoia
NeedsAdmin: True
OpsecSafe: True
MinPSVersion: 2
Background: True
Traceback (most recent call last):
File "./empire", line 20, in <module>
main.cmdloop()
File "/home/pasv/Empire/lib/common/empire.py", line 183, in cmdloop
cmd.Cmd.cmdloop(self)
File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
stop = self.onecmd(line)
File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
return func(arg)
File "/home/pasv/Empire/lib/common/empire.py", line 285, in do_agents
a.cmdloop()
File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
stop = self.onecmd(line)
File "/usr/lib/python2.7/cmd.py", …
=> Fixed module template to reflect required OutputExtension parameter

lib/stagers/macro.py
The "LegacyMacro" option allows the user to specify if the macro will be used in an Office 97-2003 document (i.e. ".xls" extension) or a modern Office document (i.e. ".xlsm" extension).  This is accomplished by changing the initial "Document_Open" function to "Auto_Open".  We have had good success with the legacy document types, presumably since the icon and extension are more familiar to users.
Tested and working on Windows 7 Enterprise.  I know this isn't a huge change, but if you need any additional clarification just let me know.
=> Added "LegacyMacro" option for Office 97-2003 compatibility 

lib/stagers/macro.py
Renamed Auto_Open() to AutoOpen() in the macro stager
https://support.microsoft.com/en-us/kb/286310
=> Corrected a typo preventing the autorunning macro from automatically running

data/module_source/privesc/Invoke-BypassUAC.ps1
Specifying Mandatory Level Name instead of SID can lead to false-negative result (for non-latin names, as for me - cyrillic). Changed to SID
=> Specifying Mandatory Level SID at Invoke-BypassUAC

lib/modules/privesc/directuac.py
Added DirectUAC module.
Description:
Leverages Start-Process' -Verb runAs option inside a loop to prompt the user for a high integrity context before running the agent code.
UAC will report Powershell is requesting Administrator privileges. Because this does not use the BypassUAC DLLs, it should not trigger any AV alerts.
Should be noted that the user needs to have Administrator rights in order for this attack to be successful.
=> Privesc - DirectUAC

setup/cert.sh
This is my first pull request (anywhere), so please let me know if I did this wrong.  Awesome project!
As you can see, this is a very simple modification.  Just removes the requirement for user input when generating the SSL key/cert by hardcoding the country to US and leaving the other options as default.  I figured this out last year for a project of my own.  
I'm wondering if you delegated the SSL generation to cert.sh because it required interaction.  If that was the reason, you could now include this task in install.sh if you wanted to.  
Demo after change: 
```
root@sethsec:/opt/Empire/setup# ./cert.sh
[*] Certificate written to ../data/empire.pem
```
=> Made SSL key/cert generation non-interactive

setup/install.sh
python-pip isn't installed by default on Kali docker images.
=> Update install.sh to install python-pip

setup/setup_database.py
Does something similar to #83 for non-interactive installation and creation of the database.
Sample run with Install.sh on a Ubuntu 14.04 box
```
~/empire/setup# STAGING_KEY=RANDOM ./install.sh
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-m2crypto is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
swig is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Requirement already …
```
=> allow for setup automation

data/module_source/collection/Invoke-Inveigh.ps1, lib/modules/collection/inveigh.py
Direct copy/paste of Invoke-Inveigh function from current standalone
version of Inveigh.  This version contains a number of
additions/changes/bug fixes. There are two primary additions that may be
useful to Empire users. The first is that 1122334455667788 is no longer
used as the default challenge over HTTP since it's now getting flagged
by SEP and maybe others. The default behavior is a random challenge for
each request. A specific challenge can also be specified through the
'challenge' parameter. The second is the ability to set a run time so
that collection/inveigh will auto-exit after a specified number of
minutes. On the python side, I have added the additional relevant
parameters and flipped the module to opsec safe since no files are
created on disk.
=> Synced collection/inveigh with current standalone Inveigh code

data/module_source/lateral_movement/Invoke-InveighRelay.ps1, lib/modules/lateral_movement/inveigh_relay.py
This module is a direct copy/paste of the Invoke-InveighRelay function
from the standalone version of Inveigh. The module will relay incoming
HTTP NTLMv2 authentication requests to an SMB target. If authentication
is successful and the user is a local administrator on the target
system, the specified command should be executed on the target PSexec
style. This module can be used with or without collection/inveigh. If
collection/inveigh is used, ensure that HTTP is disabled in
collection/inveigh. If this module is used without collection/inveigh,
another method will need to be employed to trigger incoming HTTP
requests.
This module has been successfully tested with Empire's  launcher
one-liner to establish additional agents. In testing I observed a delay
(30 seconds or so) between the …
=> Added Inveigh's HTTP NTLMv2 to SMB relay as an Empire module

data/module_source/exfil/Invoke-EgressCheck.ps1, lib/modules/exfiltration/egresscheck.py
This PR is for a module which will generate a large number of TCP and/or UDP connections to a given target on a specified port range. The main use case is an attempt to bruteforce egress opportunities (e.g. due to firewall misconfigurations) between the compromised host and another host under your control. 
I designed it with https://github.com/stufus/egresscheck-framework in mind, but any target listener would of course be absolutely fine. The specific details and background can be found at https://github.com/stufus/egresscheck-framework/blob/master/README.md and this module is more or less the powershell equivalent of https://github.com/rapid7/metasploit-framework/pull/6296. 
```
(Empire: exfiltration/egresscheck) > info
Name: Invoke-EgressCheck
Module: exfiltration/egresscheck …
```
=> Add Egress Checking Traffic Generator Module

data/module_source/situational_awareness/network/powerview.ps1
This function identifies AD groups which have the 'managedBy' attribute set (which will be the DN of a user who is allowed to manage the group) and is based on my initial msf module (https://github.com/rapid7/metasploit-framework/pull/6375). 
AD groups can be managed by otherwise low privileged users by setting the 'Managed By' attribute:
This is routinely used for distribution groups, but it turns out that security groups also support this option. If the 'manager can update membership list' option is set, it allows that user to add members to the group. This has two implications:
1. If your user happens to be the manager of a group with this option set, you can add yourself or any other user to the group. 
2. You could maintain Domain Admins persistence by setting the Domain Admins group …
=> Identify Managed AD Security Groups

data/module_source/collection/Invoke-Inveigh.ps1, data/module_source/collection/Invoke-InveighBruteForce.ps1, data/module_source/lateral_movement/Invoke-InveighRelay.ps1, data/module_source/privesc/Invoke-Tater.ps1, lib/modules/collection/inveigh.py, lib/modules/collection/inveigh_bruteforce.py, lib/modules/lateral_movement/inveigh_relay.py, lib/modules/privesc/tater.py
I updated collection/inveigh and lateral_movement/inveigh_relay to the Inveigh 1.1 functions. The relay function just contains a bugfix and the addition of a RunTime parameter. The Inveigh function has a lot of additions compared to the current Empire version including wpad.dat, cleartext basic creds capture, and the ability to respond to HTTP requests with customized HTML.
collection/inveigh_bruteforce is a new module. It can perform NBNS spoofing across subnets (Hot Potato style) as well as perform targeted NBNS spoofing without admin access.
privesc/tater is also a new module for the powershell version of the Potato privesc.
There are a few parameters that I haven't been exposing to Empire. I don't have anything exposed that relies on files (HTTPS, fileoutput, serving local content …
=> Inveigh 1.1 and Tater Modules

data/module_source/exploitation/Exploit-Jenkins.ps1, lib/modules/exploitation/exploit_jenkins.py, lib/modules/lateral_movement/jenkins_script_console.py
- Added Exploit-Jenkins.ps1 for running commands on a Jenkins Script console that does not have authentication enabled.
- exploit_jenkins.py will run single commands against a Jenkins host that can be either Linux or Windows.
- jenkins_script_console.py will deploy an Empire agent on to a Windows Jenkins host.
=> Modules for unauthenticated access to Jenkins Script Consoles to run OS commands

lib/modules/credentials/mimikatz/extract_tickets.py
You don't need elevation to extract kerberos tickets
=> No need for elevated

data/module_source/code_execution/Invoke-MetasploitPayload.ps1, lib/modules/code_execution/invoke_metasploitpayload.py
Adding my Invoke-MetasploitPayload module. This lets you execute a wide variety of metasploit payloads easily through powershell, not just reverse listeners.
=> adding the invoke-metasploitpayload module

data/module_source/privesc/Invoke-MS16032.ps1, lib/modules/privesc/ms16-032.py
Edited the Invoke-MS16-032 local exploit to work with Empire. Couldn't use Base64 stager as it wouldn't fit inside the 1024 max length of lpCommandLine. Link to original PowerShell PoC by @FuzzySec:
https://github.com/FuzzySecurity/PowerShell-Suite/blob/master/Invoke-MS16-032.ps1
Important to note: "The exploit is pretty reliable, however ~1/6 times it will say it succeeded but not spawn a shell."
=> MS16-032 local privesc for Empire

setup/install.sh
Simply added a few "-y" flags to the "apt-get" commands  in order to allow installation without user interaction. This will be especially useful if someone would like to Dockerize Empire (which I would like to do next).
These are insanely negligible changes, but feedback is welcome regardless. Thanks so much for all of y'alls hard work on this! 
--Andrew
=> Simple enhancements to installation script to allow unattended installation

lib/modules/management/spawnas.py
Sometimes credentials which we are going to use are not able to create file in %TEMP% which leads to "Access denied" error for spawnas module (it's blocked by UAC).
I chagned the path from %TEMP% to %PUBLIC% and now everything works great even from low privilege account.
=> Change paths from %TEMP% to %PUBLIC% for spawnas module

data/module_source/collection/Invoke-Inveigh.ps1, data/module_source/collection/Invoke-InveighBruteForce.ps1, data/module_source/lateral_movement/Invoke-InveighRelay.ps1, data/module_source/privesc/Invoke-Tater.ps1, lib/modules/collection/inveigh.py, lib/modules/collection/inveigh_bruteforce.py, lib/modules/lateral_movement/inveigh_relay.py, lib/modules/privesc/tater.py
Sync of Empire Inveigh and Tater modules with [Inveigh 1.1.1](https://github.com/Kevin-Robertson/Inveigh/releases/tag/1.1.1) and the current [Tater](https://github.com/Kevin-Robertson/Tater/commit/1753e6201cdc7b0a5a27b26e5e7512bcec1235a0) standalone version. Most of the changes were just formatting cleanup. From an Empire standpoint, Inveigh's new ConsoleUnique and ConsoleStatus parameters may be useful. ConsoleUnique (on by default) will only display unique challenge/response captures. ConsoleStatus allows for having Inveigh display full lists of unique captures and some other useful information at set intervals. Syncing this parameter with RunTime will also display the lists on exit. This should help those that copy/paste the hashes from the Empire console since they can now just grab a …
=> Sync with Inveigh 1.1.1 and current Tater

empire
The REST API won’t start due to a bug:
<code>./empire --rest --username "emp" --password "emp"
[*] Loading modules from: /mnt/hgfs/cjones/Empire/lib/modules/
Starting Empire RESTful API on port: 1337
RESTful API token: 2bjmeuwa6pr6yy4x0n88rauyyl1nve7cekdgkefh Traceback
(most recent call last): File "/usr/lib/python2.7/logging/init.py",
line 853, in emit msg = self.format(record) File
"/usr/lib/python2.7/logging/init.py", line 726, in format return
fmt.format(record) File "/usr/lib/python2.7/logging/init.py", line 465,
in format record.message = record.getMessage() File
"/usr/lib/python2.7/logging/init.py", line 329, in getMessage msg = msg
% self.args TypeError: %d format: a number is required, not str Logged
from file _internal.py, line 87 </code>
After casting the port from a string to …
=> Cast port from string to int when starting REST service

lib/common/stagers.py
Powershell Empire (.NET by default) uses a special HTTP/1.1 header (Expect: 100-continue) when doing a POST request, which is not happily supported by Squid 2.7 and above (more info https://alpacapowered.wordpress.com/2012/06/21/squid-expect-100-continue-header-issues/). Turn off the header.
=> 417 Expectation failed error fix

setup/install.sh
Ran into a situation where python-pip wasn't installed on a deb based box, so I've added python-pip to the unknown section of the install script.
Also moved the various apt-get install commands to just one line so it's a bit cleaner.
=> adding python-pip to unknown deb and moved apt-get commands to one line

data/module_source/situational_awareness/network/Invoke-SMBAutoBrute.ps1, lib/modules/situational_awareness/network/smbautobrute.py
The script performs "smart" brute forcing of domain accounts by ensuring that new users are queried for each password brute. Lockouts are avoided as the user query retrieves users whose badPwdCount attribute is less than (LockoutThreshold - 2) with the PDC as the source. For each brute force attempt, all DCs are queried for the badPwdCount of the user in question as that attribute is not replicated. The current user's bad password count is the highest number found from amongst all the DCs. The PDC is the target of all brute force attempts. 
Confirmed working on PowerShell v2+ and from a lowpriv account.
=> Adding SMB auto-brute module

changelog, data/module_source/credentials/dumpCredStore.ps1, lib/modules/credentials/enum_cred_store.py
This module allows for plaintext credential extraction for the current interactive user. It dumps the plaintext generic credentials from the Credential Manager Store. Although these credentials are stored in Windows Vault, a non privileged user can access their own credentials, so this module can be run to extract passwords for the current interactive user. An elevated user context is not needed.
=> Adding credentials module to extract the current interactive user's Credential Manager credentials.

data/module_source/situational_awareness/network/Invoke-ARPScan.ps1
c# code was removed and dll importation is made using powershell reflection in order to avoid creating temporary files on disk.
=> ArpScanning with reflection

data/agent/agent.ps1
Fixed a bug due to the type of quotations used. The code used in the generate_agent function of lib/listeners/http.py incorrectly matched the $Profile variable in data/agent/agent.ps1. This caused the generated agent not to be updated with the Empire listener's DefaultProfile values before being sent to the client. Changed the quotations in agent.ps1 to match the quotation in the generate_agent function's code where `code = code.replace('$Profile = "/admin/get.php,/news.php,/login/process.php|Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"', "$Profile = \"" + str(profile) + "\"")`
=> Quotation Type Bug

lib/modules/python/persistence/osx/mail.py, lib/modules/python/privesc/multi/bashdoor.py, lib/modules/python/privesc/osx/piggyback.py
**Sudo Piggyback**
This works by default up to El Capitan.  When you use sudo, it is not bound to your TTY and has a 5 minute timer from which you can use sudo again without a password.  This script clears the sudo timer, monitors the directory which holds the sudo timestamp, and once it notices a modification (Which means the user ran sudo) it triggers a launcher using sudo, sending back a root shell.  This is nice because nothing is dropped.
**Mail Persistence**
This module works by creating a rule in Mail.app to trigger an Empire stager when an email is received with a specified trigger word.  
It detects to version of OS X/MacOS in use, and first attempts to write the rule in the location where iCloud syncs mail rules.  In the absence of that, it writes the rule to the standard …
=> Module - Sudo Piggyback + Mail Persistence + Bash Profile Backdoor

lib/common/empire.py, lib/common/helpers.py
This fixes prompt line wrapping when using ansi escape codes in a prompt and scrolling through history. Readline needs to know which characters to ignore (ignore_start, ignore_end) when calculating the prompt length.
=> fix prompt line wrapping

lib/modules/python/collection/osx/screenshot.py
Fix harcoded path in the OSX screenshot module. The capture was always stored in `/tmp/out.png` instead of the value supplied by the user.
Should fix #465 
Cheers ! :skull_and_crossbones: 
TPOSOW
=> Fix harcoded path, should resolv #465

data/misc/hop.php, lib/listeners/http.py, lib/listeners/http_hop.py
Fixes issue #370.
Tested on Python 2.7.5, CentOS 7.2, and PHP 5.4.45 (for the hop server)
hop.php now adds a header with the name of its hop listener, and the hop address is passed to generate_agent().
=> Fix agent staging over http_hop listeners.

data/module_source/credentials/Invoke-Kerberoast.ps1
When Get-SPNTicket receives a user object, if that user has multiple SPNs then the call to KerberosRequestorSecurityToken is failing because it is being fed an ResultPropertyValueCollection rather than a single SPN string, For this reason, Invoke-Kerberoast was very often returning the same wrong hash for many SPNs.
The proposed change fixes this bad behaviour. ;)
=> Fixed Get-SPNTicket multiple user SPNs bug

lib/listeners/http.py, lib/listeners/http_com.py
Hi guys !
Recently, during a test, I was facing a connection problem between a client's LAN and my company's LAN. The initial connexion was performed but I could not run commands on the target (lastseenTime was always equals to checkinTime).
After a ~~long and painful~~ debugging session I figured out that the proxy between our LANs was applying a strict caching policy. My fix is to add HTTP headers in order to tell the proxy to not cache these pages.
Thanks for your amazing tool, version 2.0 is really powerfull ! :1st_place_medal: :smile: 
TPOSOS
=> Add HTTP headers to avoid proxy caching

data/module_source/python/lateral_movement/socks_source.py, lib/modules/python/lateral_movement/multi/socks.py
When executed, this module connects back to a designated AlmondRocks server under SSL. The AlmondRocks server acts as a SOCKSv5 proxy, and multiplexes all SOCKS communications over the single SSL connection to/through the target, enabling any SOCKSv5 client (e.g. curl, proxychains) to extend past NAT devices into the target network.
This is based on the following work:
https://github.com/klustic/AlmondRocks
** Server Usage **
$ ./almondrocks.py server -d -t 8443 --cert cert.pem --key key.pem
** Empire Usage **
set HOST 192.168.20.10
set PORT 8443
set Agent ...
=> Added a module for SOCKSv5 proxying

lib/common/encryption.py
Hi !
I've found a bug in your implementation of PKCS#7 padding. In the issue #458, I suspected a padding problem. Thus, by surrounding [this line](https://github.com/EmpireProject/Empire/blob/2.0_beta/data/agent/agent.ps1#L592 ) with a `try/catch` structure, it's possible to understand the cause of the bug. Indeed, the message caught was "Padding is invalid and cannot be removed"
According the [RF5652](https://tools.ietf.org/html/rfc5652#section-6.3), you have to pad like this :
```
01 -- if lth mod k = k-1
02 02 -- if lth mod k = k-2
.
.
.
k k ... k k -- if lth mod k = 0
```
where `lth` is the length of the input and `k` the size of the block in byte (16 for Empire). The interesting case is when `lth mod k = 0`, in this case, you have to pad with `k` times the `k` value.
However, …
=> Fix PKCS7 padding to be RFC compliant

data/module_source/credentials/Invoke-SessionGopher.ps1, lib/modules/powershell/credentials/sessiongopher.py
SessionGopher is a purely PowerShell tool that finds and decrypts saved session information for remote access tools. It uses WMI so it can be run remotely, and its best use case is finding Unix systems and jump boxes.
It works by querying the HKEY_USERS hive for all users who have logged onto a domain-joined box at some point. It extracts PuTTY, WinSCP, SuperPuTTY, FileZilla, and RDP saved session information and passwords. It has a built-in WinSCP password decryptor, and also deobfuscates and extracts FileZilla and SuperPuTTY passwords. When run in `Thorough` mode, it searches all drives for PuTTY private key files (.ppk) and extracts all relevant private key information, including the key itself, as well as for Remote Desktop (.rdp) and RSA (.sdtid) files.
SessionGopher has remote …
=> SessionGopher: PowerShell RDP, WinSCP, PuTTY, SuperPuTTy, FileZilla, .ppk, .rdp, .sdtid session extractor & password decryptor

lib/stagers/windows/ducky.py
On my last engagement, cmd.exe was blocked everywhere, but powershell.exe wasn't. 
I just added an option to choose the interpreter you want to use (defaulted to powershell), this should be more effective in the field. Instead of hardcoding, i just added an option (defaulting to powershell) that can change that parameter.
=> Modified the ducky stager to use custom interpreter

lib/modules/powershell/credentials/sessiongopher.py, lib/modules/powershell/privesc/ms16-032.py
The template is pre-populated with "Agent to grab a screenshot from" but that description does not apply for these modules.
=> Change Agent option description [Typo]

.gitignore, empire, lib/common/empire.py
Heya,
This addresses #507. Tracking down the problem also highlighted a bigger issue with the rest API: due to the way listeners are now loaded in Empire 2.0 (they're threads) there is no way for the rest API to keep track/interact with the listeners if it's started after the main empire console.
The laziest solution (and the most viable one, unless I'm missing something), is to start the restful API with the main empire menu object.
This shouldn't have broken anything but I do recommend testing it just in case.
Cheers guys, hope y'all are doing well
=> Fixed RESTAPI

data/module_source/privesc/Invoke-MS16135.ps1, lib/modules/powershell/privesc/ms16-135.py
Hi guys!
This PR adds a new way to perform privilege escalation (to SYSTEM) via MS16-135 (CVE-2016-7255). All credit goes to @FuzzySecurity (for the powershell implementation) and @tinysec (for the initial PoC), kudos to you two :+1:. The powershell module is just a modified version of b33f's [one](https://github.com/FuzzySecurity/PSKernel-Primitives/tree/master/Sample-Exploits/MS16-135), modified in order to spawn a child and elevate this child with SYSTEM token.
**This exploit has limitations :**
- This exploit is x64 only
- In order to trigger the bug, the exploit performs some fast windows switching with keystrokes simulations. The victim's desktop may flash.
- Because of that, the exploit only works on unlocked session.
- A named pipe is created between the child and the parent
- …
=> Add privesc module MS16-135

lib/common/stagers.py, lib/modules/powershell/persistence/elevated/wmi_updater.py
This module is based on the module powershell persistence/elevated/wmi but instead of running a stager, it fetches a file on the web/network and executes it. The idea is you put a launcher.bat (for example) accessible over internet and the agent will fetch it and run it. It allows to drop the database, change completely the Empire version, recreate a launcher.bat, put it in the same place and you agent will come back online to the new server. You don't need to keep the same certificate and all.
As an example, I saw this comment for release 1.5:
WARNING: this release modifies part of the backend database schema, so do not apply this update if you have existing agents on your Empire server. You will need to run ./setup/reset.sh to reinitialize the database.
This wmi_updater module fixes …
=> Added wmi_updater module

setup/setup_database.py
I'd tried to run Empire on the Windows 10 host. There was a problem with path separators. This fix makes setup script to work properly
=> fix install path separator

lib/modules/powershell/exfiltration/exfil_dropbox.py
This module allows for exfiltration using Dropbox. This was inspired by and ported to powershell 2 from Laurent Kempe's blog post here: http://laurentkempe.com/2016/04/07/Upload-files-to-DropBox-from-PowerShell/  
The module takes a source file, a target path in Dropbox, and  a Dropbox API key. It will upload the source file on the agent to the target path of the dropbox account. 
Tested on Windows 7 and Windows 10.
=> Addition of DropBox Exfil Module

lib/modules/python/collection/osx/prompt.py
When you use an empire launcher from within a sandboxed application in OSX (for example Office 2016 macros) many of the modules wont work. However, the prompt module can work with some modification to the osascript call. When the SandboxMode option is true, a different osascript is fired which I removed the 'tell app [App Name]' scripts out because you don't have the ability to talk to other applications in the sandbox. It fires a Display Box prompt from the context of the current application with the "System Preferences" icon and text prompting the user to enter their password to update the application.
=> Added 'SandboxMode' to evade Apple Sandbox protection on applescript

lib/listeners/dbx.py, lib/listeners/http.py, lib/listeners/http_com.py, lib/listeners/http_foreign.py, lib/listeners/http_hop.py, lib/listeners/http_mapi.py
This uses the ScriptBlock logging bypass described [here](https://cobbr.io/ScriptBlock-Logging-Bypass.html) and [shown in this gist](https://gist.github.com/cobbr/d8072d730b24fbae6ffe3aed8ca9c407) to avoid creating ScriptBlock logs. It's important to note that the bypass itself **is** logged (along with the rest of the stager until IEX is called).
Thought I'd submit a PR for this separately from the behemoth of a PR that my last one was, hopefully this one's a bit easier to manage!
=> Bypass ScriptBlock Logging

lib/listeners/http.py
on certain systems when launching the python stager, a bunch of warnings are thrown, and it would be stealthier if that wasn't the case. This change just stops printing warnings.
=> Silencing warnings

lib/common/empire.py, lib/common/messages.py
This pull request adds functionality described in issue #598. Changes in `empire.py` handle suffixing of modules when tab completing as well as stripping the asterisks when module names are passed to various methods.
As stated in issue #598, feel free to reject this if it fails to add value to the project. It has made my life easier when tab completing module names.
=> Add asterisk to modules requiring elevated context when tab completing search/usemodule (Issue 598)

data/module_source/credentials/Invoke-Kerberoast.ps1
Changed the Write-Output line to print just the $HashFormat and not the whole PS object. This way you get output that you can directly copy/paste into a file that you send to hashcat/john without any other modification.
=> Invoke-Kerberoast: Print hashes only. Formatting with a text editor is no longer required.

empire
**# ./empire -v**
2.0
**# python --version**
Python 2.7.13
**# uname -a**
Linux 4.9.0-kali3-amd64 #1 SMP Debian 4.9.16-1kali1 (2017-03-24) x86_64 GNU/Linux
**Details**
The api/admin/login doesn't authenticate properly - args passed from commandline are arrays and args fetched from db are just strings. These differences lead to wrong authentication process which results "HTTP/1.0 401 UNAUTHORIZED" response when username or password is fetched from db. 
My fix helps to authenticate properly without difference if the credentials are passed from commandline or not.
=> RESTfulAPI - api/admin/login fix

empire
```python
certPath = os.path.abspath("./data/")
context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
context.load_cert_chain("%s/empire-chain.pem" % (certPath), "%s/empire-priv.key" % (certPath))
app.run(host='0.0.0.0', port=int(port), ssl_context=context, threaded=True)
```
=> Fixed global name 'ssl' is not defined

empire, lib/common/empire.py, lib/modules/powershell/situational_awareness/network/powerview/get_group_member.py
Heya,
As the title says, the GroupName option was required when executing the get_group_member module. This is fine unless we want to query the members of a group by the group SID instead of the name. 
Edit: also, seems like ec13f26056d8048db6f86a69e5f50bee0dc5b78c broke the RESTful API again, reverted that commit.
Cheers
=> Removed GroupName as required option in get_group_member module,  reverted a commit that broke the RESTful API

setup/install.sh
in macOs sierra, "M2Crypto" library is still missing after running the install.sh
=> adding M2Crypto library to install.sh

lib/modules/powershell/situational_awareness/network/powerview/get_domain_policy.py
The output from this module looked like this and wasn't very helpful:
Name  : System Access
Value : {PasswordComplexity, MaximumPasswordAge, MinimumPasswordLength, ForceLog
offWhenHourExpire...}
Name  : Version
Value : {signature, Revision}
Name  : Kerberos Policy
Value : {TicketValidateClient, MaxTicketAge, MaxRenewAge, MaxClockSkew...}
Name  : Unicode
Value : {Unicode}
Name  : Registry Values
Value : {MACHINE\System\CurrentControlSet\Control\Lsa\NoLMHash}
We (@DisK0nn3cT and I) added an option called "ExpandObject" where you could make the output show the details contained in the powershell object. For example:
set ExpandObject System Access
Gives the following output:
Name  : PasswordComplexity
Value : {1}
Name  : MaximumPasswordAge
Value : {42}
Name  : MinimumPasswordLength
Value : …
=> added option to expand ps object in order to view domain policy details

lib/common/agents.py, lib/common/empire.py, lib/modules/powershell/collection/keylogger.py
Having the logged keystrokes spewed onto the screen while trying to use the same agent for other things is messy. This changes the PowerShell keystroke logger to log keys to Empire/downloads/AGENTNAME/keystrokes.txt instead. This keeps all the keystrokes in one place and you can use "tail -f keystrokes.txt" to watch the keystrokes in real time.
=> Modified the PowerShell keylogger to write to local file instead of stdout

lib/stagers/windows/macro.py
Hi!
This PR fixes a typo in the macro stager (avoid the overwriting of the `macro` variable).
EDIT : I also fix quotes, [similar to this fix](https://github.com/EmpireProject/Empire/pull/674/commits/f6afafe40ffa81d135998598ccb239c497db4888)
TPWSOS :sunflower:
=> Fix macro launcher

lib/stagers/windows/launcher_vbs.py
vbscript string literals require double-quotes.
=> Fixes vbscript string literal quoting.

data/agent/stagers/http.ps1, lib/listeners/http.py
Kudos to @malcomvetter for suggesting the solution implemented here.
Currently, when adding a host header via the .Net framework, as is done in the PowerShell multi/launcher,  the host name gets added to two places:
1) The HTTP header
2) The Server Name Indication (SNI) extension of the TLS client hello
The SNI is always sent in cleartext, giving away the true hostname that you are using behind your domain front. This code change simply adds a request to the root of the domain front before adding the host header, allowing the TLS connection to complete. Subsequent requests reuse this pre-established TLS connection. Therefore, adding the host name header at his point results in the value only being added to the HTTP header and not showing up in the client hello.
=> Hide true host name when using domain fronting

data/module_source/credentials/Invoke-Kerberoast.ps1
Myself and a colleague spoke at DerbyCon about some recent Kerberos research we have done.  This PR is the result of that research, and allows users to pull AES tickets when a service account is configured to encrypt TGS tickets with AES.  You may notice, I only modified the hashcat output, as john is going to be more complicated.  John's hash format lacks definition and doesn't account for the possibility of multiple tgs hash types.  As far as I'm concerned that is a problem for the folks at john to figure out.  The password used for all of the following examples is "Weakpass1"
Testing:
```powershell
PS C:\EmpirePath > klist purge;Import-Module .\Invoke-Kerberoast.ps1; invoke-kerberoast -OutputFormat Hashcat|fl
SamAccountName       : rc4_svc
DistinguishedName    : CN=RC4 …
```
=> Aes kerberoast

lib/listeners/dbx.py, lib/listeners/http.py, lib/listeners/http_com.py, lib/listeners/http_foreign.py, lib/listeners/http_hop.py, lib/listeners/http_mapi.py
Changes a few things:
* Only attempts ScriptBlock logging bypass and AMSI bypass if PS 3.0+ (should reduce the errors thrown on PS 2)
* Checks if ScriptBlock is enabled and vuln to logging bypass, executes it if so
* If not, uses the auto-logging bypass
=> Improved ScriptBlock logging bypasses

lib/common/agents.py, lib/common/helpers.py, lib/listeners/http.py
Integrates notifications to be sent to a Slack channel via the Slack API by using the new helper slackMessage() function. When an agent calls home for the first time a message will be sent to the slack channel setup in the listener settings. 
The required parameters are
- SlackToken: a token generated for your specific slack instance
- SlackChannel: a channel or user to send notifications to
- SlackText: the message to be sent
Screenshots:
=> Slack Integration - Notification for new Agents

data/module_source/collection/Get-ChromeDump.ps1
Hi!
The three main modifications are : 
- Replace `Format-Table` by `Format-List` in order to pretty-print the output
- Add `ORIGIN_URL` , because for http basic auth `ACTION_URL ` is empty
- Add `SCHEME` to show the auth type ([extract from Webkit' sources](https://github.com/adobe/chromium/blob/master/webkit/forms/password_form.h#L45-L50))
Example :
```
[*]CHROME PASSWORDS
ORIGIN_URL : https://www.facebook.com/login.php
ACTION_URL : https://www.facebook.com/login.php
PWD        : verylongpasswordisverylongverylongpasswordisverylong
USER       : verylongusernameisverylong@verylongtldisverylong.com
SCHEME     : HTML
ORIGIN_URL : https://basic.auth.redacted.com/
ACTION_URL :
PWD        : 8asicHttpP@ssw0rd
USER       : admin
SCHEME     : BASIC          
```
(redirect to dev, see #724 ) …
=> Improve Get-ChromeDump

lib/common/empire.py
When attempting to switch Modules it will try to set the current Agent for the
new module that will be used. However, this fails when switching from
`external/generate_agent.py` because it does not have this option within the
`self.module.options`.
Therefore, I changed it to check if the `Key` exists within `self.module.options`
and if it does not exist it will be set to `''`.
=> Fix #749 - Add check for 'Agent' in self.module.options

data/module_source/credentials/Invoke-PowerDump.ps1
Fixed the bug where the hashes are not being extracted correctly when LM is disabled and history is enabled.
Rather than relying on length, LM and NT headers are checked. Four bytes at 0xa0 show if LM exists and four bytes at 0xac show if NT exists. Details on this known issue can be found in the following whitepaper from blackhat:
https://media.blackhat.com/bh-us-12/Briefings/Reynolds/BH_US_12_Reynods_Stamp_Out_Hash_WP.pdf
This same bug has been fixed in other frameworks sharing the code:
https://github.com/rapid7/metasploit-framework/pull/4233
https://github.com/trustedsec/social-engineer-toolkit/pull/98
https://github.com/samratashok/nishang/pull/3
=> Invoke-PowerDump bug - corrupt hash fix

lib/modules/python/management/multi/spawn.py, lib/modules/python/persistence/osx/CreateHijacker.py, lib/modules/python/persistence/osx/RemoveDaemon.py, lib/modules/python/persistence/osx/launchdaemonexecutable.py, lib/modules/python/persistence/osx/loginhook.py, lib/modules/python/privesc/multi/sudo_spawn.py, lib/modules/python/privesc/osx/piggyback.py, lib/stagers/multi/bash.py, lib/stagers/multi/pyinstaller.py, lib/stagers/osx/applescript.py, lib/stagers/osx/application.py, lib/stagers/osx/ducky.py, lib/stagers/osx/launcher.py, lib/stagers/osx/pkg.py, lib/stagers/osx/safari_launcher.py, lib/stagers/osx/teensy.py
This PR includes some tidying of the use of the term Empyre.  It is left in the Readme and changelogs for historical purposes.  Most of the changes are informational or comments.  A few of the changes rename functions or file locations.  Those changes seem to be contained within the following files:
```
/lib/stagers/multi/pyinstaller.py
/lib/stagers/osx/teensy.py
```
=> Code cleanup from Empyre merge 

lib/modules/powershell/exfiltration/exfil_dropbox.py
Invoke obfuscation changed the function signature for generate, but this module wasn't updated, or was reverted to the old signature at somepoint. 
Probably worth reviewing all the modules to make sure they all have the correct function signature.
=> fix broken call to generate  on dropbox exfil module, caused by invoke-obfuscation changes

data/agent/stagers/dropbox.py, data/agent/stagers/http.py
Hi!
I've investigating about the issue #586 and found the root cause of the problem. As @xorrior suggested the bug is similar to a previous issue (#458).
So my main modifications are : 
- Fix the padding (see #492)
- Fix the encryption flow. Indeed, in the original code, the padding is added at blocks level. The correct way to padd is to work at the plaintext level.
If you want to reproduce the bug, just type `shell a 2>&1` in a python agent. You should have no output in your Empire session because the output length matches the case where the padding is incorrect. With this PR, you'll be able to see the result of the command.
It was very fun to dig into the code!
TPWSOS :sunflower: 
PS: I don't test the dropbox listener, if someone can test before merging thx.
=> Fix padding error in stagers, should fix #586

empire
Drawbacks right now:
- no validation beyond all fields being present and the `credtype` being either "hash" or "plaintext"
- creds are added to DB one at a time, which is slow for large batches
Not sure what the best way is to update the wiki; let me know and I'll go ahead and do that too.
This PR closes #764.
=> Add REST endpoint to allow adding creds to DB via POST request

lib/listeners/http.py
This PR fixes the following problem.
Empire Version: 2.2
OS Information: Kali 
```
(Empire: listeners/http) > set ProxyCreds 1:1
(Empire: listeners/http) > execute
[*] Starting listener 'http11'
[+] Listener successfully started!
```
When a new session is about to be established, I've got the following error:
```
(Empire: listeners/http) > [2017-10-29 09:53:36,928] ERROR in app: Exception on /t.ps1 [GET]
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, …
```
=> Fix Proxy Settings

lib/stagers/windows/launcher_xml.py
This launcher leverages MSBuild.exe to execute the powershell script. It does not require access to powershell.exe so it can be convenient to bypass applocker.
The module code is a rip off from the launcher launcher_sct.py by @subTee and @enigma0x3.
https://github.com/EmpireProject/Empire/pull/799
=> Add MSBuild.exe XML Launcher

lib/common/empire.py, lib/common/plugins.py, plugins/example.py
Still basic, but I think it's a good start.
To test:
(open empire)
```
plugins
(some output showing one row, "example", not active)
plugin example
(some output showing it's loading)
plugins
(some output, should see stars under "loaded")
help
(output, should see option "test" listed)
test
(MAGIC)
```
Current limitations:
- no unloading functionality
=> Add basic plugin functionality to Empire

.build.sh, .gitignore, .release.sh, Dockerfile, README.md, changelog
List of changes:
1. Updated README to in hopes to make install instructions a bit cleaner (can revert if needed/disagree), but it was a potential cleaner way of letting newcomers to quickly ID  the install process and docs
2. Added `.build.sh` to build the docker image 
3. Added `.release.sh` to fill out all the required data and push to Docker hub automatically. 
4. Added `Dockerfile` with comments about the build process in case others want to build the image manually.
Offical Images can be here: https://hub.docker.com/r/empireproject/empire/
Devs: Will be added to the Docker hub org.
=> Docker build release

data/agent/stagers/http_com.ps1, lib/listeners/http_com.py
Enhances the "ie_com" listener to be able to use custom HTTP headers similar to the "http" listener. Also added the option for end user to choose which HTTP header will contain the routing cookie, in the past it was "CF-RAY". Users can now choose a custom HTTP request header to store the routing cookie, but "CF-RAY" is still the default.
The intent of these changes is to allow domain fronting for the "ie_com" listener.
=> Add custom HTTP headers to ie_com listener

lib/modules/powershell/lateral_movement/invoke_sshcommand.py
Fixes `!] Exception: Stagers instance has no attribute 'installPath'` when running.
=> Update to fix invoke_sshcommand error

lib/common/listeners.py
This fix for issue https://github.com/EmpireProject/Empire/issues/825 allows to set distinct port values between the Host and Port options, thus allowing to use Empire behind port forwarding.
Currently, setting the Host option automatically modifies the Port option, and vice versa. Consequently, a single http listener can't be configured with a public port and a different listening private port.
TODO: fix the listeners: the port in the Host option is currently overwritten with the Port option if BindIP is an IPv6 address (if BindIP contains ':')
=> Allow distinct values between the Host and Port options

setup/install.sh, setup/requirements.txt
**Empire Version** current dev version 2.0
**OS Version** macOS Sierra 10.12.6
**Description**
- added macOS detection and installation of requirements.
- moved python requirements to requirements.txt file for easy of updating.
- created an install_powershell function and added macOS support through homebrew. 
- migrated away from root installation in favor of sudo 
- added a check before installing pip.
=> Small tweaks and fixes to make the installer work on macOS

empire, lib/common/encryption.py, lib/common/helpers.py, lib/common/packets.py, setup/install.sh, setup/setup_database.py
This PR addresses the request made in #707.  I chose to use [cryptography](https://github.com/pyca/cryptography) for the crypto library as it is very mature(as python goes) and under heavy development and it is very likely to be installed already.  The only place that cryptography is actually used is in ```encryption.py```.  The use of ```random```(previously used by pycrypto's random function) is replaced by ```os.urandom```, in the places where keys or IVs are being generated(this is is cryptography's preferred solution to generating pseudo-random key material), in some cases I have swapped out PyCrypto's random function for python's standard library random.  This second use of random do not relate to direct use within crypto.
Testing:
I manually walked through the old AES functions and …
=> Swap out PyCrypto for Cryptography

empire
Heya,
This is a fix to the API which should resolve #822 and the 'taskID' issue with DeathStar (https://github.com/byt3bl33d3r/DeathStar/issues/29).
The `get_agent_result` API call now returns a JSON object with the module/command output and it's respective `taskID`.
For example, here's what will be returned after running the `powershell/management/get_domain_sid` module:
```
{
results: {   
'AgentName': 'LCA9E6DM',
'AgentResults':  { 
{'results': 'S-1-5-21-1049426096-2728124650-4150323340', 'taskID': 1}
}
}
}
```
Thanks
=> Added TaskID variable to "get_agent_results" API call (Resolves #822 and issue with DeathStar)

lib/listeners/dbx.py, lib/listeners/http.py
This will first look for templates at `os.path.join(self.mainMenu.installPath, '/data/agent/stagers')`, then `os.path.join(self.mainMenu.installPath, './data/agent/stagers')`. The first should work for docker, and the second should work outside docker.
Kinda weird, though, since `installPath` should make this work either way... but that's for later investigation. (just now noticed it)
=> Include Docker and non-docker paths in template search, fix #904

empire
This will allow e.g. a javascript app to fetch resources from the Empire API even if it's not hosted at the same URI as the Empire API (which it likely won't be, since the Empire API can't host arbitrary things).
Since there's a token required to access every endpoint anyway, I don't believe this poses a security risk.
=> add CORS * header to all REST API responses

empire
We found that the TaskIDs were being skipped and generated improperly. Changed this to pull results from the results table and preserve the proper TaskIDs
=> TaskIDs fix for RESTAPI

lib/modules/python/lateral_movement/multi/ssh_command.py, lib/modules/python/lateral_movement/multi/ssh_launcher.py
Some SSH clients use a more verbose password prompt: "Password for user@pfSense.domain.local:". This patch makes the parent process wait for any string starting with "Password" and ending with ":"
=> More robust password prompt handler

lib/common/empire.py, lib/common/listeners.py, lib/common/messages.py, setup/setup_database.py
What it says on the tin.
I haven't had a change to test this with redirectors, as I'm not familiar with how Empire manages them yet. I'm pretty sure I didn't do anything that would break them, but if someone could spot-check me I'd appreciate it.
This DOES change the database schema (adding a column to the listeners table).
=> Add new options for listener management

lib/modules/powershell/lateral_movement/invoke_psexec.py
Hi all,
The invoke_psexec module is bugged when a custom command is provided instead of using the launcher and it raises a `module produced an empty script` error. I think someone forgot to paste the right code in the if statement :laughing:
:sunflower:
=> fix the invoke_psexec module

lib/common/empire.py
PR to add database output to csv and log files. Post-engagement (or even mid-engagement) reporting activities are sometimes difficult to call up. Attempting to find first-check in, or see a current/end state of credentials without starting empire can be difficult. More frustrating is trying to develop a "master narrative timeline". Currently each agent records its activity in a agent.log. Trying to add these all together in a master timeline is near impossible without going to the DB. This report function joins multiple tables together and creates the "master.log". Master.log will be updated at a later time to identify when an agent checked in. Currently represented as "none"
**sessions.csv:**
```
SessionID, Hostname, User Name, First Check-in …
```
=> Add "report" to main menu, adding some simple reporting

lib/modules/powershell/collection/minidump.py
Hi,
Simple PR to allow dumping a process from an unprivileged session with the minidump module. For example it's really useful to dump the VPN client's process (and "strings" for credentials) from an non Administrator user. Besides that, the logic within the module to handle `ProcessName` and `ProcessId` is buggy and I think it needs to be rewritten...
🌻
=> Modify minidump module to allow non-admin to dump process

data/agent/agent.py
Ok.  Let's try this again - 1 change / bug fix per request.
Python Empire agent has a bug in how it calculates packet offsets.  The length field is not included in the equation.  This results in a 4 byte overlap and a failure in the process_packet method of agent.py if multiple commands are entered over the duration of one beacon.
**Prior behavior:**
(Empire: LXF5HAKU) > sleep 30
delay/jitter set to 30/0.0
(Empire: LXF5HAKU) > shell ls
(Empire: LXF5HAKU) > shell uname
<command fails> internally a processTasking exception is thrown if the line is uncommented.
**New behavior: (after change)**
(Empire: LXF5HAKU) > sleep 30
delay/jitter set to 30/0.0
(Empire: LXF5HAKU) > shell ls
(Empire: LXF5HAKU) > shell uname
(Empire: LXF5HAKU) >
Desktop
Documents
Downloads
Music
Pictures
Public
src …
=> fix bug in calculation of packet offset in python agent

data/agent/agent.py
Add support for && and ; characters in shell commands in the Python Empire agent.  This is an enhancement.  Prior behavior did not support shell commands with those characters in them.
**New behavior:**
(Empire: MROXAHQX) > shell ls; uname
(Empire: MROXAHQX) >
Desktop
Documents
Downloads
Music
Pictures
Public
src
Templates
Videos
Linux
..Command execution completed.
(Empire: MROXAHQX) > shell ls && uname
(Empire: MROXAHQX) >
Desktop
Documents
Downloads
Music
Pictures
Public
src
Templates
Videos
Linux
..Command execution completed.
=> add support for && and ; characters in python agent

setup/install.sh
On the correct branch this time I think :) 
Fixes an apparent reversal of stretch and jessie sources.
=> Refer to correct release names for debian powershell package sources

setup/install.sh, setup/requirements.txt, setup/reset.sh
This is a fix for the docker image, as the automated build (it is automated right?) creates an image that does not work.
I have not built the docker container myself, but I have re-run the install.sh script on it. It reinstalls without errors now, so it should work when being built as well.
EDIT: Didn't read README before submitting. I can't get the dev branch to install correctly on any of my systems, so I am forced to stick with master. I am aware that this needs to be submitted to the dev branch, sorry about that.
=> Fix for #994 (Docker image broken)

data/module_source/credentials/Invoke-Kerberoast.ps1
Configurable sleep using the Sleep (in seconds) parameter between ticket requests to lower the noise the attack creates towards the Kerberos service (event id '4769').
=> Added Kerberoast feature to perform a sleep between ticket requests

Dockerfile
Hello,
The clean command should be in the same layer as the install command. Otherwise, the APT cache is stored in the layer of "RUN apt install" and the "RUN apt clean" instruction is not reducing image size.
For more info see : https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run
Regards
=>  Reduce size and layers (Dev branch)

Dockerfile
Hello,
Because we don't need to pull all the git repository, we should use --depth=1 (https://www.git-scm.com/docs/git-clone#git-clone---depthltdepthgt).
This is reducing image size and improving build speed.
Regards
=> Reduce image size (Dev Branch)

empire, lib/common/__init__.py, lib/common/agents.py, lib/common/empire.py, lib/common/events.py, lib/common/http.py, lib/common/listeners.py, lib/common/packets.py, lib/common/stagers.py, lib/listeners/dbx.py, lib/listeners/http.py, lib/listeners/http_com.py
Instead of manually inserting events into the database, this PR sets up helper functions for common events to make sure they're all identical. This also opens the door to adding more events - I'd like to eventually add some loggers so that whenever a use does something fairly major (new listener, generates agent, etc.) an event is logged.
It also adds a handler onto the dispatcher to log messages from that into the DB automatically, greatly increasing the fidelity of the events table (basically everything the user sees will end up in the events table now).
Breaking changes:
- event bodies are now saved to the DB as JSON instead of plain text descriptions of the event
ALSO, this changes the DB connection method to live in `__init__.py` for the `lib/common` modules - the DB plumbing (with …
=> Overhaul events system

setup/install.sh
Added **multiarch-support** install before libssl install
Updated **PowerShell install** to use Package Repo method (debian9)
https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#debian-9
Tested on fresh Kali full updates.
=> Install fix Kali

lib/listeners/dbx.py, lib/listeners/http.py, lib/listeners/http_com.py, lib/listeners/http_foreign.py, lib/listeners/http_hop.py, lib/listeners/onedrive.py, lib/listeners/redirector.py
which at time of writing does not…get detected by Defender yet, the original way flagged HackTool:PowerShell/PSAttack.B warning in windows Defender. New way raises no red flags (for now)
=> minuscule change in bypassing amsi

lib/modules/python/persistence/osx/LaunchAgent.py, lib/modules/python/persistence/osx/RemoveLaunchAgent.py
Re-implemented python/persistence/osx/LaunchDaemon to include lower privilege persistence. With the new 'isAdmin' logic, I opted to automatically decide where to put the executable - just my preference, we could easily revert that back to allowing use control over the executable path.
=> Added lower privilege osx launch agent persistence

Dockerfile
Fix for a weird issue when building Dockerfile : `ln: failed to create symbolic link '/usr/bin/python': File exists`
=> Fix for ln: python : file exists

README.md, lib/modules/powershell/persistence/elevated/wmi.py
The changes in this PR add a new option in the WMI Elevated Persistence Module. The concept of the new addition is 'Persistence at the attacker's request'. In essence, the persistence will be silent unless the attacker asks for it to call back.
The WMI Event Filter is looking for failed logon attempts from a specified user and will fire off the persistence as usual with this module.
This new addition requires the system to have local auditing to failed logins enabled.
To use the module the attacker should specify a username that they would like to use as the trigger, (username: redteam, for example).
After deployment, every time the specified user fails to login, the WMI consumer will fire as system.
(Failing to login to the system as the user redteam, will result in the Consumer firing …
=> Adds WMI Persistence Option

data/agent/agent.ps1, lib/common/packets.py
Hi, during my unicode bug hunting hell #542 :) I found error in data length counting. This issue affect at least linux agents. Without this fix part of the command remains in remainingData part of the packet and its not correctly executed.
=> Bugfix utf8 packet length

Dockerfile, data/misc/cSharpTemplateResources/cmd/cmd/Program.cs, empire, lib/common/empire.py, lib/listeners/http_hop.py, lib/listeners/redirector.py, lib/modules/python/persistence/osx/CreateHijacker.py, lib/modules/python/persistence/osx/launchdaemonexecutable.py, lib/stagers/multi/macro.py, lib/stagers/osx/application.py, lib/stagers/osx/dylib.py, lib/stagers/osx/macho.py, lib/stagers/osx/macro.py, lib/stagers/osx/pkg.py, setup/install.sh
SharpPick which can be generated using csharp_exe as project has a flaw, when you set Obfuscate to true there is no error handling and stager crashes. This can be fixed by changing line https://github.com/EmpireProject/Empire/blob/81487f672e8ac7ae7dbb178b4353ec3e25503c27/data/misc/cSharpTemplateResources/cmd/cmd/Program.cs#L30 to `Out-Default` which will ignore all the exceptions caused by obfuscating. There are other options to fix this, but this is certainly the simplest.
=> csharp_exe ignore exceptions caused by obfuscation

lib/listeners/http.py
Error checking for a missing CertPath would only happen when there was another error to report while creating the listener. Since a CertPath must always be present when using an https stager, this PR moves that validation earlier in the listener creation.
=> Move error checking for CertPath

data/agent/agent.ps1, data/agent/stagers/dropbox.ps1, data/agent/stagers/http.ps1, data/agent/stagers/http_com.ps1, data/agent/stagers/http_mapi.ps1, data/agent/stagers/onedrive.ps1
During debuging of the issue #1114 i found the agent bug in username utf8 encoding (and probably any other field if utf8 chars are allowed) which is send during initial phase. Tested on http stager but tried to fix on other releveant stagers too.
Without patch:
`(Empire: agents) > list`
`[*] Active agents:`
` Name            Lang  Internal IP     Machine Name    Username            Process             Delay    Last Seen`
`  ---------       ----  -----------     ------------    ---------           -------             -----    --------------------`
`  FN5D2H1X        ps    192.168.122.159 WINNIE-PC       winnie-PC\?????powershell/1864     5/0.0    2018-05-14 15:55:18`
With patch:
`(Empire: agents) > list`
`[*] Active agents:`
` Name            Lang  Internal IP     Machine Name    Username …
=> utf8 encoding fix for agent initial phase

data/module_source/code_execution/Invoke-DllInjection.ps1, data/module_source/code_execution/Invoke-ReflectivePEInjection.ps1, data/module_source/code_execution/Invoke-Shellcode.ps1, data/module_source/collection/Invoke-NetRipper.ps1, data/module_source/collection/Invoke-NinjaCopy.ps1, data/module_source/credentials/Invoke-CredentialInjection.ps1, data/module_source/credentials/Invoke-DCSync.ps1, data/module_source/credentials/Invoke-Mimikatz.ps1, data/module_source/credentials/Invoke-TokenManipulation.ps1, data/module_source/lateral_movement/Invoke-PsExec.ps1, data/module_source/management/Invoke-PSInject.ps1, data/module_source/management/Invoke-ReflectivePEInjection.ps1, data/module_source/management/Invoke-Vnc.ps1, data/module_source/privesc/Get-System.ps1, data/module_source/privesc/Invoke-BypassUAC.ps1
Windows 10 1803 adds an override on GetProcAddress that accepts a pointer to a handle, so we need to specify which function override we want. We can do this by supplying an array of argument types we want.
Tested on Win7 and Win10 1709 and 1803.
=> Fix Invoke-PSInject and Invoke-ReflectivePEInjection for Win10 1803

lib/listeners/http.py, lib/listeners/http_com.py, lib/listeners/http_foreign.py, lib/listeners/http_hop.py, lib/listeners/http_mapi.py, lib/listeners/meterpreter.py, lib/listeners/template.py
The logic for `Set Host` checks whether `Port` has been manually specified. If it has, the port remains unchanged. Unfortunately, it means that a user who specifies `Set Host https://192.168.1.1:443` during new listener creation will always have to specify the Port manually; the default value ensures `Port` is always set.
This PR removes the `:Port` from the default value for `Host` and the default value for `Port`. Now, by specifying `Set Host https://192.168.1.1:443`, both values will be set appropriately.
The only negative outcome of this that I can see is users who are accustomed to not specifying either Host or Port when creating a listener.
=> Remove listener default value for Port

lib/common/messages.py
Added a field for listener in the agents menu to help with quick situational awareness while operating within empire.
```
[*] Active agents:
Name     La Internal IP     Machine Name      Username                Process            PID    Delay    Last Seen            Listener
----     -- -----------     ------------      --------                -------            ---    -----    ---------            ----------------
103SM3DU py 127.0.1.1       ubuntu            user                    /usr/bin/python    19095  5/0.0    2018-05-17 05:59:39  http-test    
```
=> Added listener to agent list view

data/agent/agent.ps1
Hi,
when I search for bug (#1164) in my old PR I found that this PR was reverted (https://github.com/EmpireProject/Empire/commit/71a22a3b9fdc84a2348679d04ff7f5807b8c70ba). But I think that Get-Acl was already in powershell v2. Microsoft remove v2 from their PS doc but at least I found this v2 reference here http://adamringenberg.com/powershell2/get-acl. At least I fixed my previous bug if you don't accept this PR :).
=> fix for #1164

lib/modules/python/management/multi/change_process_name.py, lib/modules/python/management/multi/spawn_tty_shell.py
New pull to replace closed #1140 that had a major EBCAK error :-)
Added two modules for *nix based targets. One spawns an SSL encrypted TTY shell to a remote listener and the other enables arbitrary renaming of the Empire process (/usr/bin/python) to anything within a 15 character limit.
=> Module additions for *nix agents

setup/install.sh
Made fixes to the three issues that were blocking me from building and running under Kali 2018.4:
+ Install libicu57 as that is what Powershell requires (Kali currently only has libicu60)
+ Downgrade liburl to 1.22 per issue #1266 
+ Correct the libssl1.0.0 url and dpkg invocation per phra's PR #1219 (Supersedes #1219)
=> Updated install.sh to work with Kali 2018.4

setup/install.sh
The release number of the installed Ubuntu is stored in the file /etc/lsb-release. This number is used to select the Microsoft powershell package source list. So only one Ubuntu case is needed in the install_powershell function. Now the powershell install works also with Ubuntu 18.04.
Additional the implicit if-elif structure (only one of the if conditions is true) is converted into an explicit if-elif structure.
=> Install on Ubuntu: select the ps package source by stored version number

data/module_source/credentials/Invoke-Kerberoast.ps1
Commenting out, though it looks like it could be removed, two sections that throw errors. New-DynmaicParameter is not a function and I couldn't find it anywhere besides helper scripts on technet. 
Looks like it was first introduced in https://github.com/EmpireProject/Empire/commit/71c795a4489b133cfad7d599f9d92a1004db5934#diff-494cc831008b28a810840a12d052d51e
=> Update/Fix Invoke-Kerberoast
