changelog, lib/common/empire.py
merged branch staleAgents to master
-Allows user to list stale agents, remove stale agents and remove agents past (x) number of minutes
=> Stale agents

lib/common/empire.py, lib/common/messages.py
Updated to include correct error messaging in the stale agent menu
=> StaleAgent fix

changelog, lib/modules/collection/packet_capture.py
integrate collection/packet_capture module.
=> Packet capture

data/module_source/privesc/Invoke-WScriptBypassUAC.ps1, lib/modules/privesc/bypassuac_wscript.py
Add bypassuac with wscript.exe
=> added privesc/bypassuac_wscript

data/module_source/collection/Invoke-Inveigh.ps1, lib/modules/collection/inveigh.py, lib/modules/collection/minidump.py
https://github.com/Kevin-Robertson/Inveigh
=> Integration of Kevin Robertson's Inveigh project

changelog, lib/common/agents.py, lib/common/empire.py
Fix for 'Skywalker' exploit by @zeroSteiner
=> Skywalker fix

data/module_source/situational_awareness/host/Invoke-WinEnum.ps1, lib/modules/situational_awareness/host/winenum.py
Added Firewall Rules enumeration. Slightly modified file searches to
only pull files owned by the user. Changed formatting.
=> Modified Invoke-WinEnum

lib/modules/recon/find-fruit.py
Script to locate potentially vulnerable web services on the target network
=> Added find-fruit.py

data/module_source/recon/Find-Fruit.ps1, lib/modules/recon/find_fruit.py
Added Threading
Added FoundOnly
=> Threading Updates

setup/install.sh
Added support for Fedora, cleaned up the options for Debian and Kali. Fallback is going to Ubuntu/Debian
=> Updated install.sh to support Fedora

changelog, lib/common/agents.py, lib/common/empire.py
Main display menu now shows each time "main" menu is entered.
=> Fixed nested menu bug that caused buildup of "Agent X not active."

lib/common/agents.py, lib/common/empire.py, lib/modules/management/invoke_script.py, setup/setup_database.py
allow autorunning of a script on initial agent checkin
=> Script autorun

README.md, changelog, lib/common/empire.py
Encompases all changes since tagged 1.3.1 release.
Added 'Contribution Rules' to the README.md
=> Empire 1.4 release.

data/module_source/collection/Get-Screenshot.ps1, lib/common/empire.py, lib/modules/collection/screenshot.py
Hi, here you'll find the pull request on the dev branch.
regards.
=> screeshot in jpeg and shortcut

setup/install.sh
=> Add Pip to Ubuntu in install.sh

lib/stagers/regsvr32.py
Should be all set now.  Please test.
=> regsvr32 Stager

lib/stagers/teensy.py
Adds the capability to generate a Teensy script to run a one-liner
stage0 launcher. Similar to the existing ducky stager.
=> Teensy stager

empire
Example:
curl --insecure -i https://localhost:1337/api/map?token=sjy1x06linnmyh3q1tz9mmw8w4rqwfedu1j0dex5
HTTP/1.0 200 OK
Content-Type: application/json
Content-Length: 4058
Server: Werkzeug/0.11.9
Date: Wed, 18 May 2016 22:21:05 GMT
{
"Routes": "\r\n[ { 'delete_agent_results': [ { 'methods': 'OPTIONS,DELETE', 'url': '/api/agents/[agent_name]/results' } ] } ]\r\n[ { 'execute_module': [ { 'methods': 'POST,OPTIONS', 'url': '/api/modules/[module_name]' } ] } ]\r\n[ { 'generate_stager': [ { 'methods': 'POST,OPTIONS', 'url': '/api/stagers' } ] } ]\r\n[ { 'get_agent_results': [ { 'methods': 'HEAD,OPTIONS,GET', 'url': '/api/agents/[agent_name]/results' } ] } ]\r\n[ { 'get_agents': [ { 'methods': 'HEAD,OPTIONS,GET', 'url': '/api/agents' } ] } ]\r\n[ { 'get_agents_name': [ { 'methods': …
=> adding the /api/map endpoint to retreive all endpoint possible

lib/common/stagers.py
Reverts PowerShellEmpire/Empire#55
=> Revert "417 Expectation failed error fix"

setup/install.sh
=> Add OpenSSL to Ubuntu

lib/modules/persistence/elevated/wmi.py
s/subsubscription/subscription
=> Fixing Typo

data/module_source/exfil/Invoke-ExfilDataToGitHub.ps1, lib/modules/exfiltration/Invoke_ExfilDataToGitHub.py
Hi, sorry for all the messed up pull requests (doing this for the first time on GitHub). I wrote this module to exfiltrate files to github as part of a project at work. Please do let me know if it needs improvement.
thanks,
Nga
=> Add module to exfiltrate files and data to a GitHub repository

lib/modules/python/collection/osx/sniffer.py, lib/modules/python/privesc/multi/sudo_spawn.py
Fixes / Additions: 
- Add libpcap OS X packet capture module
- Add ability to enable / disable "SafeChecks" in side of sudo spawn
=> add osx sniffer/fix sudospawn

lib/modules/powershell_template.py
Nothing earth-shattering here, I just added some documentation explaining how you'd go about sourcing another script to use with your own inline content and added the code for only pulling in some modules from a sourced script. I also did some PEP8ing where it made sense. Also capitalization and spaces. #icanthelpmyselfstopjudging
=> Documentation, reorganization, and a touch of PEP8

lib/modules/powershell/trollsploit/wlmdr.py
I made a new branch for the 2.0 syntax. Tested working Kali 2.0 rolling.
(Replaces PR here: https://github.com/EmpireProject/Empire/pull/447)
=> Add Wlrmdr.exe Popup module (Licensing Balloons) - 2.0 beta format

lib/modules/trollsploit/wlrmdr.py
Along the same lines as trollsploit/message, this module is designed to pop up a licensing balloon in the taskbar.
Tested on:
Windows 8.1 x64
Windows 10 x64
=> Add Wlrmdr.exe Popup module (Licensing Balloons)

setup/install.sh
Added support for Arch Linux and rejigged the Unknown distro option to first, check for apt-get in case its a Debian variant but then failing if apt-get cannot be found.
=> Added support for Arch Linux and rejigged the Unknown distro option

lib/listeners/http_foreign.py
=> Add custom headers if any

changelog, lib/modules/powershell/trollsploit/get_schwifty.py, lib/stagers/windows/macro.py
Macro looks a little different every-time when generated and runs the same. was going to push to Scambled_Macro but could not find in new version. Idea could also be applied across multiple stager modules that make scripts.
=> Random Macro Variable and Method Names

empire, setup/setup_database.py
This takes care of #526, if there's a better way of doing this let me know. Cheers
=> TaskID returned in 'Agent Results' and 'Execute Module' API call

lib/common/agents.py
Added in a new way to handle the unicode return, rather than using encode function to replace characters this will allow for actual display of the ranges of unicode. Attached is an example of the emoji as the host name lol...
=> Unicode stage improvements

lib/stagers/windows/bunny.py
Fixed typo, since @viss made fun of it on Slack :)
=> Fix typo in bunny.py

data/module_source/privesc/Invoke-EnvBypass.ps1, data/module_source/privesc/Invoke-FodHelperBypass.ps1, data/module_source/privesc/Invoke-SDCLTBypass.ps1, lib/modules/powershell/privesc/bypassuac_env.py, lib/modules/powershell/privesc/bypassuac_fodhelper.py, lib/modules/powershell/privesc/bypassuac_sdctlbypass.py
https://winscripting.blog/2017/05/12/first-entry-welcome-and-uac-bypass/
=> Collection of bypass UAC modules based on fodhelper.exe, SDCLT and schtasks technique

lib/modules/powershell/situational_awareness/host/get_uaclevel.py
simple module that enumerate current UAC level
=> show current UAC level

empire, lib/modules/python/collection/osx/imessage_dump.py, lib/modules/python/collection/osx/keychaindump_chainbreaker.py, lib/modules/python/collection/osx/sniffer.py, lib/modules/python/situational_awareness/host/osx/situational_awareness.py, setup/setup_database.py
Move shebangs to `/usr/bin/env foo`
=> Fix shebangs

lib/common/pylnk.py, lib/stagers/windows/launcher_lnk.py
add launcher_lnk creates a lnk file that points to powershell.exe with a ps payload
invoke-obfuscation not yet supported
=> add launcher_lnk with ps payload

lib/listeners/dbx.py, lib/listeners/http.py, lib/listeners/http_foreign.py, lib/listeners/http_hop.py
Added some quotes to prevent generating launchers with syntax errors
=> Fixed custom proxy config in launcher code

data/module_source/management/Invoke-ReflectivePEInjection.ps1, lib/common/stagers.py, lib/modules/powershell/management/reflective_inject.py
Adding a 'generate_upload' function to stagers.py.  Was tired of manually writing upload functions for binaries to be dropped on the system.  This function will simply return powershell code to that will upload a binary to the file system.  
I've added the 'reflective_inject.py' module and 'Invoke-ReflectivePEInjection.ps1' scripts as examples on how to use the 'generate_upload' function
=> generate_upload function added to Stagers

lib/common/stagers.py, lib/listeners/dbx.py, lib/stagers/multi/launcher.py, setup/install.sh
**1. SOCKS SUPPORT FOR DROPBOX LISTENERS:**
Provides a SocksPort and SocksAddress option for the Dropbox-Listener.
Sets default SocksProxy using the PySock module and reimports the dropbox module.
Monkeypatches get_addr to prevent DNS leaking.
Works with local TOR-SOCKS5 Proxy.
**2.  ADD BypassHidden OPTION TO multi/launcher for DBX LISTENERS:**
Many AV detect the "-w 1" or "-w Hidden" option in powershell as suspicious.
Setting the "BypassHidden option in the multi/launcher to True
generates a launcher that will rather use the WindowHandler from User32.dll to
hide the powershell window instead of using "-w hidden".
Also it will remove "-w hidden","-W 1" etc. from the Launcher command string.
=> DBX Improvements (SOCKS, Hide window via WindowHandler)

lib/common/stagers.py, lib/listeners/dbx.py, lib/stagers/multi/launcher.py, setup/install.sh
Reverts EmpireProject/Empire#721
So, this works if there is a dropbox listener. However, if there is an HTTP listener, stager generation fails with:
Exception: generate_launcher() got an unexpected keyword argument 'useWindowHandler
=> Revert "DBX Improvements (SOCKS, Hide window via WindowHandler)"

empire, lib/listeners/http.py, lib/listeners/http_com.py, lib/listeners/http_mapi.py
Got it right this time, re-submission of #712.
Cheers
=>  TLS version too low fix

README.md
- Update broken module template link with links to the two existing module templates
- Change module links to be relative paths
- Add backticks around filepath
=> Update README.md to fix minor errors

lib/modules/python/collection/linux/xkeylogger.py
Here is a new PR with fixed things previously pointed out
=> Fix PR (generate function signature, opsec value)

lib/modules/powershell/credentials/mimikatz/keys.py
Copying the certificate functionality in mimi to also extract private keys.
=> Create Keys.py to extract private keys

data/agent/stagers/dropbox.py, data/agent/stagers/http.py, lib/common/encryption.py, setup/install.sh
Re-submitting #697 to dev branch.
=> Make compatible with more recent pyopenssl

data/agent/stagers/http.py, lib/common/encryption.py, lib/stagers/multi/macro.py
Take #2, to resolve conflicts with additions to version 2.2
=> Multi-Platform (Mac/Windows) Macro Stager plus MacOS Sandbox Fixes

setup/setup_database.py
Minor fix making the setup script work as expected.
=> minor changes to setup script

lib/common/empire.py, lib/modules/python/management/osx/shellb.py
Having empty bomutils folder does not allow having Empire as git submodule among other problems when git have empty dir.
=> Fix empty bomutils folder

lib/common/empire.py, lib/listeners/http.py, lib/modules/python/management/osx/shellb.py
Fix following error:
(Empire: stager/multi/launcher) > execute
[!] Exception: list index out of range
=> Fix error when ProxyCreds is set to none

setup/install.sh
Also fix issue where GCC is missing on minimal builds
=> Fix Powershell install for all supported OS

lib/common/helpers.py, lib/common/obfuscation.py, lib/listeners/dbx.py, lib/listeners/http.py, setup/requirements.txt
Pretty much what it says on the tin; python stagers from the dropbox and http listeners should be minified now. This also lays the foundation for more pyminifier work (e.g. compression, obfuscation).
=> Add pyminifier, minify stagers

setup/install.sh
=> Proposed fix for Kali Install in install.sh

lib/listeners/http.py
Usefull when outgoing connexion is less filtered than proxy ones.
=> Fix: none proxy value really means no proxy

empire
Fixed the return value for a condition that may not happen...
=> Fixed Return Value

lib/listeners/http_com.py
Alright, good news. As promised, I've modified the http_com Listener to evade Nessus plugin 99592 using the same technique described in #890. As before, I've made sure the modified Listener is able to adequately evade the Nessus plugin. 
In the following screenshot, we perform a Nessus scan using plugin 99592 against a host running an unmodified Empire http_com Listener. The scan succeeds in detecting the Listener's presence.
Running the same scan against the enhanced http_com Listener reveals that Nessus is unable to detect the http_com Listener. 
Basic unit tests seem to be passing as well, as shown in the screenshot below.
=> http_com Listener now evades Nessus plugin 99592

data/agent/agent.py
Solution for [https://github.com/EmpireProject/Empire/issues/991](https://github.com/EmpireProject/Empire/issues/991)
Test cases:
shell ls
shell ls; uname
shell ls && uname
shell echo bbb | cat > /tmp/file
Implements suggestion as noted here: https://github.com/EmpireProject/Empire/pull/992
=> Shell commands

README.md
Nobody seems to know about the wiki. 🙁 Hopefully this forestalls a bunch of questions and gets people moving more easily.
=> Add reference to wiki in readme

lib/listeners/http.py, lib/listeners/http_com.py
=> Better message for CertPath errors

Dockerfile
`# TODO: When we merge to master set branch to master`
=> Set branch to master

Dockerfile
Fix merge conflict and remove `-b master` which is for branch:master
=> Fix merge conflict

empire, lib/common/users.py
Here are the fixes ive been working off of for dev. I wanted to get these merged before you work on your new branch.
=> Websockets multiuser

Dockerfile, setup/install.sh
This fix "python - no such file or directory" and "ImportError: No module named flask".
There is still an error, see https://github.com/EmpireProject/Empire/issues/1033
=> Fix for #1033

lib/listeners/http.py, lib/listeners/http_com.py, lib/listeners/http_mapi.py, lib/stagers/windows/dde.py
#1028 This is great to can be adding additional custom headers on listeners
=> Added Additional Custom Headers Listeners For HTTP, HTTP_MAPI and HTTP_COM

lib/listeners/onedrive.py
My bad, switched to single quotes for some reason when writing the stager.
=> Fix Scriptblock logging and AMSI bypass in Onedrive stager.

lib/common/empire.py
When using individual kill for agents (rather than kill all), user input is ignored.
This commit fixes that issue.
=> Consider the user's choice when killing individual agents

lib/listeners/redirector.py, lib/stagers/multi/macro.py, lib/stagers/osx/application.py, lib/stagers/osx/dylib.py, lib/stagers/osx/macho.py, lib/stagers/osx/macro.py, lib/stagers/osx/pkg.py
Someone changed `'| python'` to `'| /usr/bin/python'` somewhere and it broke some stuff.  This fixes the rest of the unchanged instances to match.
=> Finish effort to use complete python path

data/agent/agent.ps1
Added Mode and Owner in dir command of powershell agent.
=> More informative PS agent directory listing

empire
Just a partial fix as discuss in issue #542 :(.
=> hotfix for encoding problem - issue #542

lib/common/agents.py, lib/common/empire.py, lib/common/files.py, lib/common/server.py, setup/setup_database.py
=> File transfers 3.0

data/agent/agent.ps1, data/agent/agent.py
I try to extend (both powershell and python) agent download command to accept directory as a parametr (recursively download files). I have some problems with linux (multi) stager so I cannot fully test python version (i would appreciate if someone could test python version).
=> agent download command can accept directory as a parametr

Dockerfile, empire, lib/common/empire.py, lib/common/helpers.py, lib/listeners/http.py, lib/listeners/http_com.py, lib/listeners/http_foreign.py, lib/listeners/http_hop.py, lib/listeners/redirector.py, lib/modules/python/persistence/osx/CreateHijacker.py, lib/modules/python/persistence/osx/launchdaemonexecutable.py, lib/stagers/multi/macro.py, lib/stagers/osx/application.py, lib/stagers/osx/dylib.py, lib/stagers/osx/macho.py, lib/stagers/osx/macro.py, lib/stagers/osx/pkg.py, setup/install.sh
base64 function to help hide address of call home
=> Obfuscate powershell call home address in stager code

lib/modules/external/generate_agent.py
=> Fix generate_agent.py

README.md, lib/listeners/http_com.py, lib/listeners/http_mapi.py
This extends the CertPath fix in #1102 to the `http_com` and `http_mapi` listeners. Also some minor edits to the README.md.
=> More cert path fixes

lib/common/helpers.py, lib/listeners/http.py
@xorrior This PR is fixed cookie name empty on agents and added function get_listener_cookies on helpers to get active cookies on listeners.
=> Fixed cookie name empty on agents and added function get_listener_cookies on helper

data/module_source/privesc/Get-GPPPassword.ps1, data/module_source/privesc/PowerUp.ps1
Support for Scheduledtasks TaskV2 in PowerUp (Get-CachedGPPPassword) and Get-GPPPassword
=> Support for Scheduledtasks TaskV2 in 2 files

data/module_source/management/Invoke-Phant0m.ps1, lib/modules/powershell/management/phant0m.py
=> Initial commit of Invoke-Phant0m

lib/common/helpers.py, lib/listeners/http.py
Reverts EmpireProject/Empire#1085
=> Revert "Fixed cookie name empty on agents and added function get_listener_cookies on helper"

.gitignore
setup/xar/ => setup/xar*/ in .gitignore
=> Update .gitignore to ignore any xar setup directories

data/module_source/collection/Invoke-CredentialPhisher.ps1, lib/modules/powershell/collection/toasted.py
This is the initial commit of the credential phishing module "powershell/collection/toasted". This module uses toast notifications that, upon being clicked on by the user, will prompt the user to enter in their credentials. This module differs greatly from the other windows credentials prompt module "powershell/collection/prompt" in that the credential prompt is updated to look modern and native, as well as all of the features associated with leveraging toast notifications to entice user interaction.
Relevant links:
Demo: https://blog.quickbreach.io/toasted-phish/
Original Blog Posting - https://www.fox-it.com/en/insights/blogs/blog/phishing-ask-and-ye-shall-receive/
Original Script - https://github.com/fox-it/Invoke-CredentialPhisher
Empire Adaptation of Script - …
=> Initial commit of powershell/collection/toasted
